@Backend_HostAddress = https://localhost:7021
@AccessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwibmJmIjoxNzEyODE3MzQzLCJleHAiOjE3MTI4MjA5NDMsImlhdCI6MTcxMjgxNzM0M30.1YmGXDlwMXXpyXLvP4BMrUsDOfxAa7zMW15UpSsudJc


// Login

POST {{Backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123qwe"
}

###

// Get activities

GET {{Backend_HostAddress}}/api/activity/GetActivities?ActivityType=1
Authorization: {{AccessToken}}

###

// Logout

POST {{Backend_HostAddress}}/api/auth/Logout
Authorization: {{AccessToken}}

###
