// <auto-generated />
using System;
using Core.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240411071654_Update_Table2")]
    partial class Update_Table2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.EFCore.DBEntities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("活動名稱");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int")
                        .HasComment("活動類型");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasComment("CreateAt");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasComment("DeleteAt");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasComment("UpdateAt");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int")
                        .HasComment("UpdaterId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCategoryId");

                    b.ToTable("Activities", t =>
                        {
                            t.HasComment("活動");
                        });
                });

            modelBuilder.Entity("Core.EFCore.DBEntities.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("類別名稱");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasComment("CreateAt");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasComment("DeleteAt");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasComment("UpdateAt");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int")
                        .HasComment("UpdaterId");

                    b.HasKey("Id");

                    b.ToTable("ActivityCategories", t =>
                        {
                            t.HasComment("活動類別");
                        });
                });

            modelBuilder.Entity("Core.EFCore.DBEntities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("帳號");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasComment("CreateAt");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasComment("DeleteAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("名稱");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("密碼");

                    b.Property<DateTime?>("ResetPasswordExpireTime")
                        .HasColumnType("datetime2")
                        .HasComment("重設密碼過期時間");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("重設密碼權杖");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasComment("UpdateAt");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int")
                        .HasComment("UpdaterId");

                    b.HasKey("Id");

                    b.ToTable("Admins", t =>
                        {
                            t.HasComment("後台使用者");
                        });
                });

            modelBuilder.Entity("Core.EFCore.DBEntities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("帳號");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasComment("CreateAt");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasComment("DeleteAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("名稱");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("密碼");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("刷新令牌");

                    b.Property<DateTime?>("RefreshTokenExpireAt")
                        .HasColumnType("datetime2")
                        .HasComment("刷新令牌到期時間");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasComment("UpdateAt");

                    b.Property<int?>("UpdaterId")
                        .HasColumnType("int")
                        .HasComment("UpdaterId");

                    b.HasKey("Id");

                    b.ToTable("Customers", t =>
                        {
                            t.HasComment("前台使用者");
                        });
                });

            modelBuilder.Entity("Core.EFCore.DBEntities.Activity", b =>
                {
                    b.HasOne("Core.EFCore.DBEntities.ActivityCategory", "ActivityCategory")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityCategoryId");

                    b.Navigation("ActivityCategory");
                });

            modelBuilder.Entity("Core.EFCore.DBEntities.ActivityCategory", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
